PI-832 Reduce volume size to 128GB
Due to errors relating to throughput:
```
Error: error updating Elasticsearch Domain config: LimitExceededException: Throughput must be between 250 and 593
```