Add custom serviceaccount rules for github actions
Needs to delete a deployed branch in its own subdomain
with all that that involves

specifically the default serviceaccount_rules were raising this:

```
Error: uninstallation completed with 3 error(s): ...
cannot delete resource "statefulsets" in API group "apps" ...
cannot delete resource "networkpolicies" in API group "networking.k8s.io" ...
cannot delete resource "servicemonitors" in API group "monitoring.coreos.com" ...
```