Remove cluster unused variable cluster_state_bucket
This change is outlined here: https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/compare/5.13.1...5.14.1
If left in this error will be generated:
```
Error: Unsupported argument

  on rds.tf line 5, in module "rds":
   5:   cluster_state_bucket = var.cluster_state_bucket
```