Remove rds-snapshot RDS instance
This instance is no longer required.

It was breaking the build pipeline with this error:

```
Error: error deleting Database Instance "cloud-platform-2f8c3c1ceaf0a05d": DBSnapshotAlreadyExists: Cannot create the snapshot because a snapshot with the identifier cloud-platform-2f8c3c1ceaf0a05d-finalsnapshot already exists.
	status code: 400, request id: 810dcddc-71e8-454f-96b0-2afc4c6b426b
```