Set a backup window for hmpps-book-secure-move-api-dev
We need to set an explicit backup window to ensure that it doesn't
overlap with the maintenance window.

```
executing: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources; terraform apply -auto-approve
Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources; terraform apply -auto-approve failed.

Error: Error modifying DB Instance cloud-platform-4be37a4047a3b230: InvalidParameterValue: The backup window and maintenance window must not overlap.
	status code: 400, request id: b436571c-e74b-4e12-aaf2-18a56d4c1b5a

  on .terraform/modules/rds-instance/main.tf line 104, in resource "aws_db_instance" "rds":
 104: resource "aws_db_instance" "rds" {
```