Fix dynamodb definition
Although plan was fine with the previous `dynamodb.tf` file, when
applied it resulted in this error:

```
Error: error creating DynamoDB Table: ValidationException: Invalid
KeySchema: Some index key attribute have no definition
        status code: 400, request id: XXX...
```

Removing the `range_key` line allowed `terraform apply ` to succeed.

NB: I have already applied this manually, so this PR is just to keep the
code in sync with the terraform state.