Comment out resources to unbreak apply pipeline
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/266

The error is:
```
Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources; terraform apply -auto-approve failed.

Error: error creating Kinesis Firehose Delivery Stream: ResourceInUseException: Firehose geoamey under accountId 754256621582 already exists

Error: Error describing created certificate: Expected certificate to be issued but was in state PENDING_VALIDATION

Error: error creating Kinesis Firehose Delivery Stream: ResourceInUseException: Firehose serco under accountId 754256621582 already exists
```

I think the prod environment resources need different names from the existing dev
resources.

In order to restore the apply pipeline to a working state, this change
comments out the firehose delivery stream as well as any other resources
which had not been successfully created.

This is the minimum set of changes I could make, in terms of leaving the
terraform state as close to its current state as possible.