Allow major version upgrade
Creating this RDS instance failed with:

```
Error: Error modifying DB Parameter Group: InvalidParameterCombination: cannot use immediate apply method for static parameter
```

I think allowing major version upgrade here might fix this, since that's the only significant difference I can see between this RDS instance and [this one](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf)