Chore: Bump RDS engine version for laa-hmrc-interface-production
Fix error whereby pipeline attempts to downgrade the RDS engine version from 18.3 to 18.1, which is not allowed.

```
Error: updating RDS DB Instance (cloud-platform-1e4a3d0841d520eb): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 29d33f8e-0eee-46c9-b889-2ab7d6438ee7, api error InvalidParameterCombination: Cannot upgrade postgres from 18.3 to 18.1
```