AP-6213: Disable opt_in_xsiam_logging
The `opt_in_xsiam_logging = true` option causes a db upgrade error.

```
Error: modifying RDS DB Parameter Group (cloud-platform-blah): operation error RDS: ModifyDBParameterGroup, https response error StatusCode: 400, RequestID: blah, api error InvalidParameterValue: Invalid parameter value: 1 for: log_connections allowed values are: receipt, authentication, authorization, setup_durations, all
```