Add a path to the opseng terraform IAM user
The previous PR failed to create this user.

```
Error: Error creating IAM User terraform-user-bbddf46750d979fbbcec4e6bf067d4c4: AccessDenied: User: arn:aws:iam::754256621582:user/cloud-platform/manager-concourse is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::754256621582:user/terraform-user-bbddf46750d979fbbcec4e6bf067d4c4
	status code: 403, request id: 0e2e65d7-7271-4bc7-bcfe-e210ad17fbc6
```

However, other IAM users have been created 
successfully.

Looking at others, I can see that they have a 
`path` defined, so this change adds a path to 
this IAM user, to see if that fixes the problem.