Fix conflict in terraform concourse-ci test
The error was:

FATA[0051] error running terraform on namespace cccd-dev: unable to do Terraform Plan: exit status 1

Error: Conflicting configuration arguments

  with module.read_replica[0].aws_db_instance.rds,
  on .terraform/modules/read_replica/main.tf line 114, in resource "aws_db_instance" "rds":
 114:   db_name              ...

"db_name": conflicts with replicate_source_db